import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Loader2, PackageSearch, RefreshCw, Truck, XCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { rawMessage } from "@/lib/format-error";
import { formatBRL } from "@/lib/format-currency";
import { usePermissoesTela } from "@/hooks/usePermissoesTela";
import { useAbaUrl } from "@/hooks/useAbaUrl";
import { PageShell } from "@/components/layout/PageShell";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { CardIndicador } from "@/components/ui/card-indicador";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { TabelaFetely } from "@/components/ui/tabela-fetely";
import { RodapePaginacao, lerTamanhoPaginaSalvo, type PageSizeOption } from "@/components/tabela/RodapePaginacao";
import { Skeleton } from "@/components/ui/skeleton";
import { RegularizacaoStepper } from "@/components/regularizacao/RegularizacaoStepper";
import { RegularizacaoStatus } from "@/components/regularizacao/RegularizacaoStatus";
import { RetornosRegularizacao } from "@/components/regularizacao/RetornosRegularizacao";
import { CancelarLoteDialog } from "@/components/regularizacao/CancelarLoteDialog";
import { useGerarRascunhos } from "@/components/regularizacao/useGerarRascunhos";
import type { RegularizacaoItem, RegularizacaoLote, RegularizacaoRetorno, RegularizacaoRetornoItem } from "@/components/regularizacao/types";

type ProdutoJoin = { cod_cadastro?: string | null; nome_comercial?: string | null };
const produtoJoin = (p: unknown): ProdutoJoin => Array.isArray(p) ? (p[0] as ProdutoJoin | undefined) ?? {} : (p as ProdutoJoin | null) ?? {};
export default function RegularizacaoLoteDetalhe() {
  const { id } = useParams(); const qc = useQueryClient(); const [aba, setAba] = useAbaUrl("inventario"); const { podeEditar } = usePermissoesTela("tela.regularizacao_estoque");
  const [buscaInventario, setBuscaInventario] = useState(""); const [paginaInventario, setPaginaInventario] = useState(1); const [tamanhoPagina, setTamanhoPagina] = useState<PageSizeOption>(() => lerTamanhoPaginaSalvo()); const [cancelarAberto, setCancelarAberto] = useState(false);
  const loteQ = useQuery({ queryKey: ["regularizacao", "lote", id], enabled: !!id, refetchInterval: 30_000, queryFn: async () => { const { data, error } = await supabase.from("vw_regularizacao_lote").select("*").eq("id", id ?? "").single(); if (error) throw error; return data as RegularizacaoLote; } });
  const itensQ = useQuery({ queryKey: ["regularizacao", "itens", id], enabled: !!id, queryFn: async () => { const { data, error } = await supabase.from("regularizacao_item").select("id,lote_id,sku,quantidade,quantidade_coberta,sncf_produtos(cod_cadastro,nome_comercial)").eq("lote_id", id ?? "").order("sku"); if (error) throw error; return (data ?? []).map((r) => { const produto = produtoJoin(r.sncf_produtos); return { id: r.id, lote_id: r.lote_id, sku: r.sku, quantidade: r.quantidade, quantidade_coberta: r.quantidade_coberta, cod_cadastro: produto.cod_cadastro ?? null, nome_comercial: produto.nome_comercial ?? null }; }) as RegularizacaoItem[]; } });
  const retornosQ = useQuery({ queryKey: ["regularizacao", "retornos", id], enabled: !!id, refetchInterval: 30_000, queryFn: async () => {
    // A relação aninhada é castada manualmente (tipos gerados não inferem o duplo aninhamento).
    const { data, error } = await supabase.from("regularizacao_retorno_nf").select("*,regularizacao_retorno_item(*,sncf_produtos(cod_cadastro,nome_comercial))").eq("lote_id", id ?? "").order("nf_origem_data", { ascending: false });
    if (error) throw error;
    return ((data ?? []) as unknown as (RegularizacaoRetorno & { regularizacao_retorno_item: (RegularizacaoRetornoItem & { sncf_produtos?: unknown })[] })[]).map((r) => ({ ...r, itens: r.regularizacao_retorno_item.map((item) => { const produto = produtoJoin(item.sncf_produtos); return { ...item, cod_cadastro: produto.cod_cadastro ?? null, nome_comercial: produto.nome_comercial ?? null }; }) })) as RegularizacaoRetorno[];
  } });
  const recarregar = async () => { await Promise.all([qc.invalidateQueries({ queryKey: ["regularizacao", "lote", id] }), qc.invalidateQueries({ queryKey: ["regularizacao", "itens", id] }), qc.invalidateQueries({ queryKey: ["regularizacao", "retornos", id] }), qc.invalidateQueries({ queryKey: ["regularizacao", "lotes"] })]); };
  const distribuir = useMutation({ mutationFn: async () => { if (!id) throw new Error("Lote inválido."); const { error } = await supabase.rpc("reg_lote_distribuir", { p_lote_id: id }); if (error) throw error; }, onSuccess: async () => { toast.success("Lote redistribuído."); await recarregar(); }, onError: (e) => toast.error(rawMessage(e)) });
  const criarTrs = useMutation({ mutationFn: async () => { if (!id) throw new Error("Lote inválido."); const { error } = await supabase.rpc("reg_lote_criar_trs", { p_lote_id: id }); if (error) throw error; }, onSuccess: async () => { toast.success("TRS de regularização criada."); await recarregar(); }, onError: (e) => toast.error(rawMessage(e)) });
  const lote = loteQ.data; const itens = itensQ.data ?? []; const retornos = retornosQ.data ?? [];
  const cancelado = lote?.status === "cancelado"; const podeAcao = podeEditar && !cancelado;
  const podeCancelar = podeAcao && lote && !["cancelado", "concluido"].includes(lote.status) && !lote.trs_pedido_id && !retornos.some((r) => ["gerando", "rascunho", "autorizada"].includes(r.status));
  const { pendentes, progresso, gerarTodos } = useGerarRascunhos(retornos, recarregar);
  const origensPorSku = useMemo(() => { const mapa = new Map<string, string[]>(); for (const retorno of retornos) for (const item of retorno.itens ?? []) mapa.set(item.sku, [...(mapa.get(item.sku) ?? []), `NF ${retorno.nf_origem_numero}: ${item.quantidade.toLocaleString("pt-BR")}`]); return mapa; }, [retornos]);
  const filtrados = useMemo(() => { const termo = buscaInventario.trim().toLocaleLowerCase("pt-BR"); return termo ? itens.filter((item) => `${item.cod_cadastro ?? ""} ${item.nome_comercial ?? ""} ${item.sku}`.toLocaleLowerCase("pt-BR").includes(termo)) : itens; }, [itens, buscaInventario]);
  const paginaAtual = Math.min(paginaInventario, Math.max(1, Math.ceil(filtrados.length / tamanhoPagina))); const itensExibidos = filtrados.slice((paginaAtual - 1) * tamanhoPagina, paginaAtual * tamanhoPagina);
  const cards = useMemo(() => lote ? [{ r: "Contado em SP", v: lote.pecas_inventario, n: "peças" }, { r: "Com NF de origem", v: lote.pecas_cobertas, n: "peças" }, { r: "Sem NF de origem", v: Math.max(0, lote.pecas_inventario - lote.pecas_cobertas), n: "peças", tom: lote.pecas_inventario > lote.pecas_cobertas ? "atencao" as const : "neutro" as const }, { r: "NFs de retorno", v: `${lote.nfs_autorizadas}/${lote.nfs_retorno}`, n: "autorizadas / total" }, { r: "Valor do retorno", v: formatBRL(lote.valor_retorno) }, { r: "TRS", v: lote.trs_numero ?? "—", n: lote.trs_estagio ?? undefined }] : [], [lote]);
  if (loteQ.isLoading) return <PageShell><Skeleton className="h-20 w-full" /><Skeleton className="h-48 w-full" /></PageShell>;
  if (!lote || loteQ.isError) return <PageShell><div className="rounded-md border p-10 text-center text-destructive">{rawMessage(loteQ.error)}</div></PageShell>;
  const rascunhos = retornos.filter((r) => r.status === "rascunho");
  const proximoPasso = lote.entradas_site > 0 ? <div><strong>Etapa 5 · Estoque vendável atualizado: {lote.entradas_site.toLocaleString("pt-BR")} entradas no Site SP</strong></div> : pendentes.length > 0 ? <><div><strong>Etapa 3 · Gerar os rascunhos das NFs de retorno no Bling — {pendentes.length} pendentes</strong><p className="mt-1 text-xs text-muted-foreground">Já existe um rascunho? Use Vincular na aba Retornos.</p></div>{podeAcao && <Button onClick={() => void gerarTodos()} disabled={!!progresso}>{progresso ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />{progresso}</> : "Gerar todos os pendentes"}</Button>}</> : rascunhos.length > 0 && lote.nfs_autorizadas < lote.nfs_retorno ? <div><strong>Etapa 3 · Aguardando a Eva conferir e transmitir {rascunhos.length} NF(s) no Bling</strong><div className="mt-1 text-xs text-muted-foreground">{rascunhos.slice(0, 4).map((r) => `${r.nf_retorno_numero ?? "Rascunho"} ← NF ${r.nf_origem_numero}`).join(" · ")}</div></div> : lote.status === "retornos_concluidos" ? <><strong>Etapa 4 · Criar a transferência de regularização (TRS)</strong>{podeAcao && <Button onClick={() => criarTrs.mutate()} disabled={criarTrs.isPending}><Truck className="mr-2 h-4 w-4" />Criar TRS de regularização</Button>}</> : lote.status === "transferencia_emitida" && !lote.nf_6152_numero ? <><div><strong>Etapa 4 · Abra o TRS e clique em Enviar ao Bling; a Eva emite a NF 6152</strong><p className="mt-1 text-xs text-muted-foreground">Estágio: {lote.trs_estagio ?? "—"}</p></div>{lote.trs_pedido_id && <Button asChild><Link to={`/pedidos/${lote.trs_pedido_id}`}>Abrir TRS</Link></Button>}</> : lote.nf_6152_numero ? <strong>Etapa 5 · Aguardando a entrada no estoque vendável</strong> : <strong>Etapa 2 · Distribua o inventário entre as NFs de origem</strong>;
  return <PageShell variant="dados" className="animate-casa-fade-in"><PageHeader titulo={`${lote.codigo} · ${lote.titulo}`} icone={PackageSearch} breadcrumb={[{ label: "Produto" }, { label: "Estoque" }, { label: "Regularização", to: "/estoque/regularizacao" }]} estado={<span className="flex items-center gap-2">{lote.centro_destino_rotulo}<RegularizacaoStatus status={lote.status} /></span>} acoes={<div className="flex items-center gap-2">{podeCancelar && <Button variant="outline" className="text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => setCancelarAberto(true)}><XCircle className="mr-2 h-4 w-4" />Cancelar lote</Button>}<Button asChild variant="outline"><Link to="/estoque/regularizacao"><ArrowLeft className="mr-2 h-4 w-4" />Voltar</Link></Button></div>} />
    {cancelado && <div className="rounded-md border bg-muted/50 p-4"><div className="text-sm font-medium">Lote cancelado</div>{lote.observacao && <p className="mt-1 text-sm text-muted-foreground">{lote.observacao}</p>}</div>}
    <RegularizacaoStepper status={lote.status} entradasSite={lote.entradas_site} />
    {!cancelado && <div className={`flex flex-wrap items-center justify-between gap-3 rounded-md border p-4 ${lote.entradas_site > 0 ? "border-success/30 bg-success/10" : "border-primary/30 bg-primary/10"}`}><div><div className="mb-1 text-[11px] font-medium uppercase text-muted-foreground">Próximo passo</div>{proximoPasso}</div></div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{cards.map((c) => <CardIndicador key={c.r} rotulo={c.r} valor={typeof c.v === "number" ? c.v.toLocaleString("pt-BR") : c.v} nota={c.n} tom={c.tom} compacto />)}</div>
    <Tabs value={aba} onValueChange={setAba}><TabsList><TabsTrigger value="inventario">Inventário</TabsTrigger><TabsTrigger value="retornos">Retornos</TabsTrigger><TabsTrigger value="transferencia">Transferência</TabsTrigger></TabsList>
      <TabsContent value="inventario" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-muted-foreground">Contado = o que foi contado fisicamente. Com NF de origem = peças que têm uma NF de remessa para servir de lastro ao retorno. Sem NF = precisam de outro tratamento.</p>{podeAcao && ["rascunho", "distribuido"].includes(lote.status) && <Button variant="outline" onClick={() => distribuir.mutate()} disabled={distribuir.isPending}><RefreshCw className="mr-2 h-4 w-4" />Redistribuir</Button>}</div><TabelaFetely busca={{ valor: buscaInventario, aoMudar: (v) => { setBuscaInventario(v); setPaginaInventario(1); }, placeholder: "Buscar código, produto ou SKU…" }} carregando={itensQ.isLoading} erro={itensQ.isError ? rawMessage(itensQ.error) : null} aoTentarNovamente={() => void itensQ.refetch()} total={itens.length} exibidos={filtrados.length} rotulo="produtos" vazio={{ mensagem: "Nenhum produto no inventário." }}><div className="overflow-x-auto rounded-md border"><Table><TableHeader><TableRow><TableHead>Cód. cadastro</TableHead><TableHead>Produto</TableHead><TableHead>Contado em SP</TableHead><TableHead>Com NF de origem</TableHead><TableHead>Sem NF</TableHead><TableHead>De onde veio</TableHead></TableRow></TableHeader><TableBody>{itensExibidos.map((i) => { const semNf = Math.max(0, i.quantidade - i.quantidade_coberta); return <TableRow key={i.id} className={semNf > 0 ? "bg-warning/10" : undefined}><TableCell className="font-mono text-xs whitespace-nowrap" title={i.sku}>{i.cod_cadastro ?? "—"}</TableCell><TableCell><div className="max-w-72 truncate" title={`${i.sku} — ${i.nome_comercial ?? ""}`}>{i.nome_comercial ?? "—"}</div><div className="max-w-72 truncate font-mono text-[11px] text-muted-foreground">{i.sku}</div></TableCell><TableCell className="tabular-nums">{i.quantidade.toLocaleString("pt-BR")}</TableCell><TableCell className="tabular-nums">{i.quantidade_coberta.toLocaleString("pt-BR")}</TableCell><TableCell className={semNf > 0 ? "font-medium tabular-nums text-warning" : "tabular-nums"}>{semNf.toLocaleString("pt-BR")}</TableCell><TableCell className="max-w-80 text-xs">{(origensPorSku.get(i.sku) ?? []).join(" · ") || "—"}</TableCell></TableRow>; })}</TableBody></Table><RodapePaginacao total={filtrados.length} pagina={paginaAtual} tamanhoPagina={tamanhoPagina} tela="tela.regularizacao_estoque" onPagina={setPaginaInventario} onTamanhoPagina={(n) => setTamanhoPagina(n as PageSizeOption)} /></div></TabelaFetely></TabsContent>
      <TabsContent value="retornos"><RetornosRegularizacao retornos={retornos} podeEditar={podeAcao} recarregar={recarregar} /></TabsContent>
      <TabsContent value="transferencia"><div className="space-y-4 rounded-md border p-5"><div className="grid gap-3 sm:grid-cols-3"><div><div className="text-xs text-muted-foreground">TRS</div>{lote.trs_pedido_id ? <Link className="font-medium text-primary underline" to={`/pedidos/${lote.trs_pedido_id}`}>{lote.trs_numero ?? "Abrir transferência"}</Link> : <span>—</span>}</div><div><div className="text-xs text-muted-foreground">Estágio</div><span>{lote.trs_estagio ?? "—"}</span></div><div><div className="text-xs text-muted-foreground">NF 6152 · entradas no centro</div><span>{lote.nf_6152_numero ?? "—"} · {lote.entradas_site.toLocaleString("pt-BR")}</span></div></div>{!lote.trs_pedido_id && lote.status !== "retornos_concluidos" && <p className="text-sm text-muted-foreground">Autorize todos os retornos antes de criar a transferência.</p>}{podeAcao && !lote.trs_pedido_id && lote.status === "retornos_concluidos" && <Button onClick={() => criarTrs.mutate()} disabled={criarTrs.isPending}><Truck className="mr-2 h-4 w-4" />Criar TRS de regularização</Button>}</div></TabsContent>
    </Tabs>{podeCancelar && <CancelarLoteDialog loteId={lote.id} codigo={lote.codigo} open={cancelarAberto} onOpenChange={setCancelarAberto} aoCancelar={recarregar} />}</PageShell>;
}
