import {
  ArrowDownCircle,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpCircle,
  Award,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  Calendar,
  CheckCheck,
  Circle,
  ClipboardList,
  Clock,
  Coins,
  CreditCard,
  Eye,
  FilePlus,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Filter,
  FolderArchive,
  FolderTree,
  Gift,
  GitBranch,
  GitCompare,
  HandCoins,
  HeartPulse,
  Home,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  ListChecks,
  LogOut,
  MailPlus,
  MessageCircle,
  MessageSquare,
  MessageSquareWarning,
  Monitor,
  Package,
  PackageOpen,
  Palmtree,
  Percent,
  PieChart,
  Radar,
  Receipt,
  Rocket,
  Route,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Sparkles,
  StickyNote,
  TableProperties,
  Target,
  TrendingUp,
  Truck,
  Tv,
  Upload,
  User,
  UserCog,
  UserPlus,
  Users,
  UserSearch,
  UsersRound,
  Wallet,
  Warehouse,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Mapa estatico de icones da navegacao. Doutrina MENU-VIA-TABELA: o nome do
 * icone vive na coluna sncf_navegacao.icone e e resolvido aqui.
 *
 * Por que mapa estatico e nao `import * as Icons`: o import estrela do
 * lucide-react derruba o tree-shaking e leva o pacote inteiro pro bundle.
 * Aqui entram so os 79 icones que a tabela usa de fato.
 *
 * Icone novo na tabela: acrescente aqui. Sem entrada, cai no fallback Circle
 * e o console avisa — nunca quebra a tela.
 */
const ICONES: Record<string, LucideIcon> = {
  ArrowDownCircle,
  ArrowDownToLine,
  ArrowLeftRight,
  ArrowUpCircle,
  Award,
  Banknote,
  BarChart3,
  BookOpen,
  Boxes,
  Brain,
  Building2,
  Calendar,
  CheckCheck,
  ClipboardList,
  Clock,
  Coins,
  CreditCard,
  Eye,
  FilePlus,
  FileSignature,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Filter,
  FolderArchive,
  FolderTree,
  Gift,
  GitBranch,
  GitCompare,
  HandCoins,
  HeartPulse,
  Home,
  Inbox,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  ListChecks,
  LogOut,
  MailPlus,
  MessageCircle,
  MessageSquare,
  MessageSquareWarning,
  Monitor,
  Package,
  PackageOpen,
  Palmtree,
  Percent,
  PieChart,
  Radar,
  Receipt,
  Rocket,
  Route,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Sparkles,
  StickyNote,
  TableProperties,
  Target,
  TrendingUp,
  Truck,
  Tv,
  Upload,
  User,
  UserCog,
  UserPlus,
  Users,
  UserSearch,
  UsersRound,
  Wallet,
  Warehouse,
  Zap,
};

export function resolverIcone(nome: string | null | undefined): LucideIcon {
  if (!nome) return Circle;
  const found = ICONES[nome];
  if (!found) {
    console.warn(`[iconesNavegacao] icone "${nome}" nao esta no mapa. Acrescente em src/config/iconesNavegacao.ts`);
    return Circle;
  }
  return found;
}
