CREATE OR REPLACE VIEW public.vw_recebivel_gestao AS
 SELECT v.id,
    v.numero_titulo,
    v.numero_parcela,
    v.total_parcelas,
    v.conta_id,
    v.cliente,
    v.meio_pagamento,
    v.banco_nome,
    v.banco_recebimento_id,
    v.nf_id,
    v.nf_numero,
    v.data_compra,
    v.data_vencimento,
    v.valor,
    v.status_gestao,
    v.data_liquidacao,
    v.liquidacao_realizada,
    v.parceiro_id,
    v.liquidacao_confirmada_banco,
    v.pago,
    v.liquidado,
    v.conciliado,
    v.valor_efetivo,
    v.valor_juros,
    v.valor_desconto,
    v.valor_bruto,
    v.data_vencimento_original,
    v.venc_renegociado,
    v.dias_prorrogado,
    v.data_pagamento,
    v.pedido_id,
    v.pedido_ref,
    v.mes_competencia,
    v.gera_caixa,
    v.tem_prova_bancaria,
    v.data_recebimento_efetiva,
    v.fonte_data_recebimento,
    v.data_pagamento_banco,
    v.data_divergente,
    v.mes_caixa_efetivo,
    v.estado_gestao,
    v.estado_rotulo,
    v.estado_ordem,
    v.estado_cor,
    v.estado_descricao,
    v.estado_terminal,
    v.estado_em_aberto,
    v.meio_pedido,
    v.meio_pedido_nome,
    v.meio_divergente,
    v.faturado,
    v.data_liquidacao_prevista,
    v.desvio_previsao_dias,
    v.data_caixa_projetada,
    v.mes_caixa_projetado,
    v.eixo_prova,
    v.eixo_status,
    v.compensado_por,
    v.eh_inadimplencia,
    v.eixo_recebimento,
    v.eixo_prazo,
    v.eixo_instrumento,
    v.estado_em_aberto AND COALESCE(c.tem_vencimento, true) AND COALESCE(b.data_vencimento, t.data_vencimento_nf, t.data_vencimento_original) < CURRENT_DATE AS eh_inadimplente,
    v.condicao_parcelamento,
    c.codigo AS carteira_codigo,
    c.nome AS carteira_nome,
    c.ordem AS carteira_ordem,
    c.ancora AS carteira_ancora,
    c.previsao_confiavel AS carteira_previsao_confiavel,
    c.rotulo_data AS carteira_rotulo_data,
    c.gera_caixa AS carteira_gera_caixa,
    t.data_vencimento_nf,
    b.data_vencimento AS data_vencimento_instrumento,
    COALESCE(b.data_vencimento, t.data_vencimento_nf, t.data_vencimento_original) AS data_vencimento_vigente,
    b.data_vencimento - COALESCE(t.data_vencimento_nf, t.data_vencimento_original) AS desvio_registro_dias,
    b.data_vencimento IS NOT NULL AND t.data_vencimento_atual = b.data_vencimento AND t.data_vencimento_atual <> t.data_vencimento_original AS sobreposicao_instrumento,
    t.data_vencimento_atual <> t.data_vencimento_original AND (b.data_vencimento IS NULL OR t.data_vencimento_atual <> b.data_vencimento) AND (t.justificativa_renegociacao IS NOT NULL OR t.modalidade_renegociacao IS NOT NULL) AS renegociacao_humana,
        CASE
            WHEN c.codigo = 'SAFRA-BOLETO'::text AND (v.eixo_instrumento = ANY (ARRAY['registrado'::text, 'conciliado'::text, 'liquidado_banco'::text])) THEN 'firme'::text
            WHEN c.codigo = 'SAFRA-BOLETO'::text AND v.eixo_instrumento = 'remessa_gerada'::text THEN 'em_registro'::text
            WHEN c.codigo = 'SAFRA-CARTAO'::text AND t.autorizacao_cartao IS NOT NULL THEN 'firme'::text
            WHEN c.codigo = 'SAFRA-CARTAO'::text THEN 'sem_prova'::text
            WHEN c.codigo = ANY (ARRAY['PIX-PRAZO'::text, 'CONTA'::text, 'CONSIGNADO'::text]) THEN 'promessa'::text
            ELSE NULL::text
        END AS qualidade,
    v.data_recebimento,
    v.dinheiro_no_banco,
    v.recebimento_rotulo,
    v.recebimento_ordem,
    v.recebimento_classe,
    v.recebimento_tooltip,
    v.prazo_rotulo,
    v.prazo_ordem,
    v.prazo_classe,
    v.prazo_classe_texto,
    v.instrumento_rotulo,
    v.instrumento_ordem,
    v.instrumento_classe,
    v.instrumento_tooltip,
    v.data_liquidacao_real,
    v.aguardando_credito,
    v.relogio_pontualidade,
    v.dias_atraso_adquirente
   FROM vw_recebivel_b2b v
     JOIN titulo_a_receber t ON t.id = v.id
     LEFT JOIN carteira c ON c.id = t.carteira_id
     LEFT JOIN LATERAL ( SELECT bb.data_vencimento
           FROM titulo_boleto bb
          WHERE bb.titulo_id = t.id
          ORDER BY bb.created_at DESC
         LIMIT 1) b ON true;